define(['require'], function (require) {
    return function (types) {
        return [
            // Booleans
            { name: 'True', type: types.Boolean, value: '1' },
            { name: 'False', type: types.Boolean, value: '0' },

            // Mathematical constants
            { name: 'ebPi', type: types.Double, value: '3.141592653589793238462643383279' },
            { name: 'ebE', type: types.Double, value: '2.718281828459045235360287471352' },

            // Keys
            { name: 'ebKeyBack', type: types.Integer, value: '8' },
            { name: 'ebKeyTab', type: types.Integer, value: '9' },
            { name: 'ebKeyReturn', type: types.Integer, value: '13' },
            { name: 'ebKeyEnter', type: types.Integer, value: '13' },
            { name: 'ebKeyShift', type: types.Integer, value: '16' },
            { name: 'ebKeyCtrl', type: types.Integer, value: '17' },
            { name: 'ebKeyAlt', type: types.Integer, value: '18' },
            { name: 'ebKeyCapsLock', type: types.Integer, value: '20' },
            { name: 'ebKeyEscape', type: types.Integer, value: '27' },
            { name: 'ebKeySpace', type: types.Integer, value: '32' },
            { name: 'ebKeyPageUp', type: types.Integer, value: '33' },
            { name: 'ebKeyPageDown', type: types.Integer, value: '34' },
            { name: 'ebKeyEnd', type: types.Integer, value: '35' },
            { name: 'ebKeyHome', type: types.Integer, value: '36' },
            { name: 'ebKeyLeft', type: types.Integer, value: '37' },
            { name: 'ebKeyUp', type: types.Integer, value: '38' },
            { name: 'ebKeyRight', type: types.Integer, value: '39' },
            { name: 'ebKeyDown', type: types.Integer, value: '40' },
            { name: 'ebKeyInsert', type: types.Integer, value: '45' },
            { name: 'ebKeyDelete', type: types.Integer, value: '46' },
            // Numbers
            { name: 'ebKey0', type: types.Integer, value: '48' },
            { name: 'ebKey1', type: types.Integer, value: '49' },
            { name: 'ebKey2', type: types.Integer, value: '50' },
            { name: 'ebKey3', type: types.Integer, value: '51' },
            { name: 'ebKey4', type: types.Integer, value: '52' },
            { name: 'ebKey5', type: types.Integer, value: '53' },
            { name: 'ebKey6', type: types.Integer, value: '54' },
            { name: 'ebKey7', type: types.Integer, value: '55' },
            { name: 'ebKey8', type: types.Integer, value: '56' },
            { name: 'ebKey9', type: types.Integer, value: '57' },
            // Letters
            { name: 'ebKeyA', type: types.Integer, value: '65' },
            { name: 'ebKeyB', type: types.Integer, value: '66' },
            { name: 'ebKeyC', type: types.Integer, value: '67' },
            { name: 'ebKeyD', type: types.Integer, value: '68' },
            { name: 'ebKeyE', type: types.Integer, value: '69' },
            { name: 'ebKeyF', type: types.Integer, value: '70' },
            { name: 'ebKeyG', type: types.Integer, value: '71' },
            { name: 'ebKeyH', type: types.Integer, value: '72' },
            { name: 'ebKeyI', type: types.Integer, value: '73' },
            { name: 'ebKeyJ', type: types.Integer, value: '74' },
            { name: 'ebKeyK', type: types.Integer, value: '75' },
            { name: 'ebKeyL', type: types.Integer, value: '76' },
            { name: 'ebKeyM', type: types.Integer, value: '77' },
            { name: 'ebKeyN', type: types.Integer, value: '78' },
            { name: 'ebKeyO', type: types.Integer, value: '79' },
            { name: 'ebKeyP', type: types.Integer, value: '80' },
            { name: 'ebKeyQ', type: types.Integer, value: '81' },
            { name: 'ebKeyR', type: types.Integer, value: '82' },
            { name: 'ebKeyS', type: types.Integer, value: '83' },
            { name: 'ebKeyT', type: types.Integer, value: '84' },
            { name: 'ebKeyU', type: types.Integer, value: '85' },
            { name: 'ebKeyV', type: types.Integer, value: '86' },
            { name: 'ebKeyW', type: types.Integer, value: '87' },
            { name: 'ebKeyX', type: types.Integer, value: '88' },
            { name: 'ebKeyY', type: types.Integer, value: '89' },
            { name: 'ebKeyZ', type: types.Integer, value: '90' },
            // Numpad
            { name: 'ebKeyNumpad0', type: types.Integer, value: '96' },
            { name: 'ebKeyNumpad1', type: types.Integer, value: '97' },
            { name: 'ebKeyNumpad2', type: types.Integer, value: '98' },
            { name: 'ebKeyNumpad3', type: types.Integer, value: '99' },
            { name: 'ebKeyNumpad4', type: types.Integer, value: '100' },
            { name: 'ebKeyNumpad5', type: types.Integer, value: '101' },
            { name: 'ebKeyNumpad6', type: types.Integer, value: '102' },
            { name: 'ebKeyNumpad7', type: types.Integer, value: '103' },
            { name: 'ebKeyNumpad8', type: types.Integer, value: '104' },
            { name: 'ebKeyNumpad9', type: types.Integer, value: '105' },
            { name: 'ebKeyMultiply', type: types.Integer, value: '106' },
            { name: 'ebKeyAdd', type: types.Integer, value: '107' },
            { name: 'ebKeySubstract', type: types.Integer, value: '109' },
            { name: 'ebKeyDecimalPoint', type: types.Integer, value: '110' },
            { name: 'ebKeyDivide', type: types.Integer, value: '111' },
            // Function keys
            { name: 'ebKeyF1', type: types.Integer, value: '112' },
            { name: 'ebKeyF2', type: types.Integer, value: '113' },
            { name: 'ebKeyF3', type: types.Integer, value: '114' },
            { name: 'ebKeyF4', type: types.Integer, value: '115' },
            { name: 'ebKeyF5', type: types.Integer, value: '116' },
            { name: 'ebKeyF6', type: types.Integer, value: '117' },
            { name: 'ebKeyF7', type: types.Integer, value: '118' },
            { name: 'ebKeyF8', type: types.Integer, value: '119' },
            { name: 'ebKeyF9', type: types.Integer, value: '120' },
            { name: 'ebKeyF10', type: types.Integer, value: '121' },
            { name: 'ebKeyF11', type: types.Integer, value: '122' },
            { name: 'ebKeyF12', type: types.Integer, value: '123' },

        ];
    };
});